name: biobb_wf_md_setup
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_structure_utils==5.1.0
  - biobb_chemistry==5.1.0
  - biobb_analysis==5.1.0
  - biobb_io==5.1.0
  - biobb_model==5.1.0
  - biobb_gromacs==5.1.0
  - plotly
  #Â - python=3.10
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview
  - simpletraj